version: "3"
services:
    selenium:
        image: selenium/standalone-chrome:3.141.59-20200826
        container_name: uxa-selenium
        ports:
            - "4444:4444"
        environment:
            - http_proxy=
            - https_proxy=
